// NexCivic AI Image Analysis Engine (Sprint 7 Cached)
import { currentVisionProvider, VisionAnalysisResult } from "./visionProvider";

const visionAnalysisCache = new Map<string, VisionAnalysisResult>();

/**
 * Computes a simple string hash signature for an image file or Base64 string
 */
function getImageSignature(imageSource: File | string): string {
  if (typeof imageSource === "string") {
    return `str_${imageSource.length}_${imageSource.substring(0, 50)}`;
  }
  return `file_${imageSource.name}_${imageSource.size}_${imageSource.lastModified}`;
}

/**
 * Analyzes uploaded complaint image using active vision provider with caching
 */
export async function analyzeComplaintImage(imageSource: File | string): Promise<VisionAnalysisResult> {
  const cacheKey = getImageSignature(imageSource);

  if (visionAnalysisCache.has(cacheKey)) {
    console.log("[ImageAnalysisEngine] Returning cached vision analysis result.");
    return visionAnalysisCache.get(cacheKey)!;
  }

  const result = await currentVisionProvider.analyzeImage(imageSource);

  // Guarantee explicit reasoning text
  if (!result.reasoning) {
    result.reasoning = `Visual detection generated by ${result.providerName} based on geometric and color contrast signatures.`;
  }

  visionAnalysisCache.set(cacheKey, result);
  return result;
}

/**
 * Clears the image analysis cache if needed
 */
export function clearVisionAnalysisCache(): void {
  visionAnalysisCache.clear();
}
